// Bible Word Scramble - Expanded Word Database (1000+ words)
const WORD_DATABASE = {
  easy: {
    old: [
      { word: "ADAM", hint: "The first man created by God", verse: "Genesis 2:7" },
      { word: "EVE", hint: "The first woman, mother of all living", verse: "Genesis 3:20" },
      { word: "NOAH", hint: "Built the ark to save his family", verse: "Genesis 6:9" },
      { word: "ARK", hint: "Noah's great wooden vessel", verse: "Genesis 6:14" },
      { word: "CAIN", hint: "Son of Adam who slew his brother", verse: "Genesis 4:1" },
      { word: "ABEL", hint: "Son of Adam, a keeper of sheep", verse: "Genesis 4:2" },
      { word: "MOSES", hint: "Led the Israelites out of Egypt", verse: "Exodus 3:10" },
      { word: "DAVID", hint: "Shepherd boy who became king", verse: "1 Samuel 16:13" },
      { word: "RUTH", hint: "She said 'Where you go I will go'", verse: "Ruth 1:16" },
      { word: "JOB", hint: "Suffered greatly but kept his faith", verse: "Job 1:1" },
      { word: "EDEN", hint: "The garden where Adam and Eve lived", verse: "Genesis 2:8" },
      { word: "SINAI", hint: "Mountain where Moses received the law", verse: "Exodus 19:20" },
      { word: "EGYPT", hint: "Land of the Pharaohs", verse: "Genesis 12:10" },
      { word: "ISAAC", hint: "Son born to Abraham and Sarah", verse: "Genesis 21:3" },
      { word: "JACOB", hint: "His name was changed to Israel", verse: "Genesis 32:28" },
      { word: "LEAH", hint: "Jacob's first wife", verse: "Genesis 29:23" },
      { word: "ESAU", hint: "Twin brother who sold his birthright", verse: "Genesis 25:25" },
      { word: "LEVI", hint: "Third son of Jacob and Leah", verse: "Genesis 29:34" },
      { word: "JUDAH", hint: "From whose tribe Jesus descended", verse: "Genesis 29:35" },
      { word: "SARAH", hint: "Abraham's wife who laughed at the promise", verse: "Genesis 18:12" },
      { word: "LOT", hint: "Abraham's nephew rescued from Sodom", verse: "Genesis 13:1" },
      { word: "HAM", hint: "Son of Noah, father of Canaan", verse: "Genesis 9:18" },
      { word: "SHEM", hint: "Son of Noah, ancestor of Semitic peoples", verse: "Genesis 9:18" },
      { word: "BOAZ", hint: "Kinsman-redeemer who married Ruth", verse: "Ruth 2:1" },
      { word: "NAOMI", hint: "Mother-in-law of Ruth", verse: "Ruth 1:2" },
      { word: "SAUL", hint: "First king of Israel", verse: "1 Samuel 9:2" },
      { word: "LAMB", hint: "Animal used for sacrifice, symbol of Jesus", verse: "Exodus 12:3" },
      { word: "DOVE", hint: "Symbol of peace sent from the ark", verse: "Genesis 8:8" },
      { word: "FIRE", hint: "God appeared to Moses in this form", verse: "Exodus 3:2" },
      { word: "ROCK", hint: "Moses struck this to bring water", verse: "Exodus 17:6" },
      { word: "GOLD", hint: "Metal used to make the golden calf", verse: "Exodus 32:4" },
      { word: "HARP", hint: "David played this before Saul", verse: "1 Samuel 16:23" },
      { word: "STAR", hint: "God promised Abraham descendants like these", verse: "Genesis 15:5" },
      { word: "RAIN", hint: "God sent this for forty days and nights", verse: "Genesis 7:12" },
      { word: "LION", hint: "Daniel was thrown into a den of these", verse: "Daniel 6:16" },
      { word: "CALEB", hint: "One of the faithful spies sent to Canaan", verse: "Numbers 13:6" },
      { word: "RAHAB", hint: "Innkeeper who hid the Israelite spies", verse: "Joshua 2:1" },
      { word: "ENOCH", hint: "Man who walked with God and was taken", verse: "Genesis 5:24" },
      { word: "JESSE", hint: "Father of King David", verse: "1 Samuel 16:1" },
      { word: "OBED", hint: "Son of Ruth and Boaz, grandfather of David", verse: "Ruth 4:17" },
    ],
    new: [
      { word: "JESUS", hint: "The Son of God, Saviour of the world", verse: "John 3:16" },
      { word: "MARY", hint: "Mother of Jesus", verse: "Luke 1:30" },
      { word: "PETER", hint: "Fisherman who became a disciple", verse: "Matthew 4:18" },
      { word: "JOHN", hint: "The beloved disciple", verse: "John 19:26" },
      { word: "PAUL", hint: "Missionary who wrote many epistles", verse: "Acts 9:3" },
      { word: "JAMES", hint: "Son of Zebedee, brother of John", verse: "Matthew 4:21" },
      { word: "MARK", hint: "Wrote the second Gospel", verse: "Acts 12:12" },
      { word: "LUKE", hint: "Doctor who wrote a Gospel and Acts", verse: "Colossians 4:14" },
      { word: "ROME", hint: "Great city Paul visited and wrote to", verse: "Romans 1:7" },
      { word: "GRACE", hint: "Unmerited favour from God", verse: "Ephesians 2:8" },
      { word: "FAITH", hint: "Assurance of things hoped for", verse: "Hebrews 11:1" },
      { word: "LOVE", hint: "Greatest commandment of all", verse: "1 Corinthians 13:13" },
      { word: "HOPE", hint: "Anchor for the soul", verse: "Hebrews 6:19" },
      { word: "CROSS", hint: "Symbol of Christ's sacrifice", verse: "Galatians 6:14" },
      { word: "ANGEL", hint: "Heavenly messenger sent by God", verse: "Matthew 1:20" },
      { word: "BREAD", hint: "Jesus called himself the bread of life", verse: "John 6:35" },
      { word: "LIGHT", hint: "Jesus said He is the light of the world", verse: "John 8:12" },
      { word: "TRUTH", hint: "Jesus said He is the way, the truth, the life", verse: "John 14:6" },
      { word: "VINE", hint: "Jesus said He is the true vine", verse: "John 15:1" },
      { word: "WORD", hint: "In the beginning was this, says John 1", verse: "John 1:1" },
      { word: "SALT", hint: "Jesus called His followers this of the earth", verse: "Matthew 5:13" },
      { word: "FISH", hint: "Jesus multiplied these to feed 5000", verse: "John 6:11" },
      { word: "LIFE", hint: "Jesus came that we might have it abundantly", verse: "John 10:10" },
      { word: "TOMB", hint: "Jesus was buried and rose from this", verse: "John 20:1" },
      { word: "WELL", hint: "Jesus spoke to the Samaritan woman at this", verse: "John 4:6" },
      { word: "WINE", hint: "Jesus turned water into this at Cana", verse: "John 2:9" },
      { word: "DOVE", hint: "Symbol of the Holy Spirit at Jesus' baptism", verse: "Matthew 3:16" },
      { word: "ANDREW", hint: "Peter's brother, first called disciple", verse: "John 1:40" },
      { word: "SILAS", hint: "Paul's companion on his second journey", verse: "Acts 15:40" },
      { word: "PRAYER", hint: "Communication with God", verse: "Matthew 6:9" },
    ],
    people: [
      { word: "ANNA", hint: "Prophetess who saw the baby Jesus", verse: "Luke 2:36" },
      { word: "SIMON", hint: "Disciple also called Peter", verse: "Matthew 10:2" },
      { word: "LYDIA", hint: "First European convert, seller of purple", verse: "Acts 16:14" },
      { word: "TITUS", hint: "Paul's companion, leader in Crete", verse: "Titus 1:4" },
      { word: "LOIS", hint: "Grandmother of Timothy", verse: "2 Timothy 1:5" },
      { word: "AQUILA", hint: "Tentmaker who worked with Paul", verse: "Acts 18:2" },
      { word: "EUNICE", hint: "Timothy's faithful mother", verse: "2 Timothy 1:5" },
      { word: "DORCAS", hint: "Woman raised from dead by Peter, made clothes for poor", verse: "Acts 9:36" },
      { word: "PHOEBE", hint: "Deaconess who carried Paul's letter to Rome", verse: "Romans 16:1" },
      { word: "CLEOPAS", hint: "Disciple who walked to Emmaus with Jesus", verse: "Luke 24:18" },
      { word: "HIRAM", hint: "King of Tyre who helped Solomon build the temple", verse: "1 Kings 5:1" },
      { word: "MIRIAM", hint: "Sister of Moses who led worship after the Red Sea", verse: "Exodus 15:20" },
    ],
    places: [
      { word: "ZION", hint: "Holy mountain, city of God", verse: "Psalm 48:2" },
      { word: "BABEL", hint: "City where languages were confused", verse: "Genesis 11:9" },
      { word: "NILE", hint: "Great river of Egypt", verse: "Exodus 1:22" },
      { word: "MOAB", hint: "Land where Ruth came from", verse: "Ruth 1:1" },
      { word: "JOPPA", hint: "City where Jonah tried to flee", verse: "Jonah 1:3" },
      { word: "CANAAN", hint: "The promised land given to Israel", verse: "Genesis 12:5" },
      { word: "GOSHEN", hint: "Region in Egypt where Israel settled", verse: "Genesis 45:10" },
      { word: "HOREB", hint: "Another name for Mount Sinai", verse: "Exodus 3:1" },
      { word: "JORDAN", hint: "River where Jesus was baptised", verse: "Matthew 3:13" },
      { word: "RAMAH", hint: "Town associated with Samuel and Rachel", verse: "1 Samuel 1:19" },
    ],
  },

  medium: {
    old: [
      { word: "ABRAM", hint: "Abraham's name before God changed it", verse: "Genesis 11:26" },
      { word: "ELIJAH", hint: "Prophet taken to heaven in a chariot of fire", verse: "2 Kings 2:11" },
      { word: "ELISHA", hint: "Elijah's successor as prophet", verse: "1 Kings 19:16" },
      { word: "GOLIATH", hint: "Giant Philistine warrior defeated by David", verse: "1 Samuel 17:4" },
      { word: "SAMSON", hint: "Judge whose strength was in his hair", verse: "Judges 13:24" },
      { word: "DELILAH", hint: "Betrayed Samson to the Philistines", verse: "Judges 16:4" },
      { word: "SOLOMON", hint: "Wisest king who built the temple", verse: "1 Kings 3:12" },
      { word: "ISAIAH", hint: "Prophet who foretold the coming Messiah", verse: "Isaiah 7:14" },
      { word: "JEREMIAH", hint: "The weeping prophet", verse: "Jeremiah 1:5" },
      { word: "EZEKIEL", hint: "Prophet known for his vision of dry bones", verse: "Ezekiel 37:1" },
      { word: "MALACHI", hint: "Last book of the Old Testament", verse: "Malachi 4:6" },
      { word: "JONAH", hint: "Prophet swallowed by a great fish", verse: "Jonah 1:17" },
      { word: "DANIEL", hint: "Survived the lion's den by faith", verse: "Daniel 6:22" },
      { word: "PHARAOH", hint: "King of Egypt who refused to let Israel go", verse: "Exodus 5:2" },
      { word: "MANNA", hint: "Bread from heaven fed to Israel", verse: "Exodus 16:15" },
      { word: "SABBATH", hint: "The seventh day of rest commanded by God", verse: "Exodus 20:8" },
      { word: "PASSOVER", hint: "Memorial feast of the Exodus", verse: "Exodus 12:11" },
      { word: "COVENANT", hint: "Sacred agreement between God and man", verse: "Genesis 9:13" },
      { word: "PROPHET", hint: "One who speaks the word of God", verse: "Deuteronomy 18:18" },
      { word: "TABERNACLE", hint: "Portable sanctuary built by Moses", verse: "Exodus 26:1" },
      { word: "OFFERING", hint: "Gift presented to God in worship", verse: "Leviticus 1:2" },
      { word: "JERICHO", hint: "City whose walls fell at a shout", verse: "Joshua 6:20" },
      { word: "BETHLEHEM", hint: "City of David, birthplace of Jesus", verse: "Micah 5:2" },
      { word: "JERUSALEM", hint: "Holy city, city of the great King", verse: "Psalm 48:1" },
      { word: "PROVERBS", hint: "Book of wisdom by Solomon", verse: "Proverbs 1:7" },
      { word: "HOSEA", hint: "Prophet whose marriage illustrated Israel's unfaithfulness", verse: "Hosea 1:2" },
      { word: "MICAH", hint: "Prophet who foretold Bethlehem as Messiah's birthplace", verse: "Micah 5:2" },
      { word: "REBEKAH", hint: "Wife of Isaac, mother of Jacob and Esau", verse: "Genesis 24:67" },
      { word: "GIDEON", hint: "Judge who defeated Midian with 300 men", verse: "Judges 7:7" },
      { word: "DEBORAH", hint: "Female judge and prophetess of Israel", verse: "Judges 4:4" },
      { word: "HANNAH", hint: "Mother of Samuel who prayed for a child", verse: "1 Samuel 1:20" },
      { word: "SAMUEL", hint: "Prophet who anointed both Saul and David", verse: "1 Samuel 3:20" },
      { word: "NATHAN", hint: "Prophet who confronted David about Bathsheba", verse: "2 Samuel 12:1" },
      { word: "JOSHUA", hint: "Led Israel into the Promised Land", verse: "Joshua 1:1" },
      { word: "HEZEKIAH", hint: "Good king who prayed and God healed him", verse: "2 Kings 20:5" },
      { word: "NAAMAN", hint: "Syrian commander healed of leprosy by Elisha", verse: "2 Kings 5:1" },
      { word: "BALAAM", hint: "Prophet whose donkey spoke to him", verse: "Numbers 22:28" },
      { word: "INCENSE", hint: "Fragrant offering burned before God", verse: "Exodus 30:7" },
      { word: "ALTAR", hint: "Stone structure where sacrifices were made", verse: "Genesis 8:20" },
      { word: "TEMPLE", hint: "Solomon built this as God's dwelling place", verse: "1 Kings 6:1" },
      { word: "FAMINE", hint: "Drove Jacob's family to Egypt for grain", verse: "Genesis 42:5" },
      { word: "PLAGUE", hint: "God sent ten of these on Egypt", verse: "Exodus 7:14" },
      { word: "POTIPHAR", hint: "Egyptian officer who bought Joseph as a slave", verse: "Genesis 37:36" },
      { word: "BATHSHEBA", hint: "Wife of Uriah whom David sinfully took", verse: "2 Samuel 11:3" },
      { word: "ABSALOM", hint: "David's rebellious son who led a coup", verse: "2 Samuel 15:10" },
      { word: "REHOBOAM", hint: "Solomon's son whose foolishness divided the kingdom", verse: "1 Kings 12:1" },
      { word: "JEROBOAM", hint: "First king of the northern kingdom of Israel", verse: "1 Kings 11:26" },
      { word: "ATHALIAH", hint: "Wicked queen who killed the royal family", verse: "2 Kings 11:1" },
      { word: "UZZIAH", hint: "King of Judah who reigned 52 years", verse: "2 Chronicles 26:3" },
      { word: "MANASSEH", hint: "Wicked king who later repented", verse: "2 Chronicles 33:1" },
    ],
    new: [
      { word: "LAZARUS", hint: "Raised from the dead by Jesus", verse: "John 11:43" },
      { word: "MARTHA", hint: "Sister of Mary and Lazarus", verse: "Luke 10:40" },
      { word: "THOMAS", hint: "The doubting disciple who touched Jesus' wounds", verse: "John 20:27" },
      { word: "MATTHEW", hint: "Tax collector who wrote the first Gospel", verse: "Matthew 9:9" },
      { word: "STEPHEN", hint: "First Christian martyr", verse: "Acts 7:59" },
      { word: "PHILLIP", hint: "Disciple who shared the gospel with the Ethiopian", verse: "Acts 8:26" },
      { word: "TIMOTHY", hint: "Paul's young protégé", verse: "1 Timothy 1:2" },
      { word: "HEROD", hint: "King who ordered the massacre of infants", verse: "Matthew 2:16" },
      { word: "PILATE", hint: "Roman governor who sentenced Jesus", verse: "John 19:6" },
      { word: "BARNABAS", hint: "Called 'Son of Encouragement'", verse: "Acts 4:36" },
      { word: "PENTECOST", hint: "Day the Holy Spirit came with fire", verse: "Acts 2:1" },
      { word: "BAPTISM", hint: "Sacrament of initiation into Christ", verse: "Matthew 28:19" },
      { word: "COMMUNION", hint: "Lord's Supper remembering Christ's sacrifice", verse: "1 Corinthians 11:24" },
      { word: "RESURRECTION", hint: "Rising from the dead on the third day", verse: "John 11:25" },
      { word: "REVELATION", hint: "Final book of the Bible; vision of John", verse: "Revelation 1:1" },
      { word: "NAZARETH", hint: "The town where Jesus grew up", verse: "Luke 2:39" },
      { word: "BETHANY", hint: "Village home of Mary, Martha, and Lazarus", verse: "John 11:1" },
      { word: "CAESAR", hint: "Roman emperor Jesus said to render unto", verse: "Matthew 22:21" },
      { word: "AGRIPPA", hint: "King before whom Paul made his defence", verse: "Acts 26:1" },
      { word: "GALILEE", hint: "Sea where Jesus walked on water", verse: "Matthew 14:25" },
      { word: "CAPERNAUM", hint: "Jesus' base of ministry in Galilee", verse: "Matthew 4:13" },
      { word: "SAMARIA", hint: "Region whose people were despised by Jews", verse: "John 4:4" },
      { word: "ANTIOCH", hint: "City where followers were first called Christians", verse: "Acts 11:26" },
      { word: "CORINTH", hint: "Greek port city with a famous church", verse: "Acts 18:1" },
      { word: "SERMON", hint: "Jesus delivered this on the mount", verse: "Matthew 5:1" },
      { word: "PARABLE", hint: "Story Jesus told to teach spiritual truth", verse: "Matthew 13:3" },
      { word: "DISCIPLE", hint: "A follower and learner of Jesus", verse: "Matthew 10:1" },
      { word: "WITNESS", hint: "One who testifies to what they have seen", verse: "Acts 1:8" },
      { word: "FASTING", hint: "Going without food as a spiritual discipline", verse: "Matthew 6:16" },
      { word: "FORGIVE", hint: "Jesus told us to do this seventy times seven", verse: "Matthew 18:22" },
      { word: "REPENT", hint: "John the Baptist's core message", verse: "Matthew 3:2" },
      { word: "EPHESUS", hint: "City of Artemis, site of a great church", verse: "Acts 19:1" },
      { word: "PHILIPPI", hint: "First European city where Paul planted a church", verse: "Acts 16:12" },
      { word: "ATHENS", hint: "Greek city where Paul preached at the Areopagus", verse: "Acts 17:15" },
      { word: "DAMASCUS", hint: "City where Paul was converted on the road", verse: "Acts 9:3" },
      { word: "EMMAUS", hint: "Village where Jesus walked with two disciples", verse: "Luke 24:13" },
      { word: "CALVARY", hint: "Place of the skull where Jesus was crucified", verse: "Luke 23:33" },
      { word: "NICODEMUS", hint: "Pharisee who came to Jesus by night", verse: "John 3:1" },
      { word: "ZACCHAEUS", hint: "Short tax collector who climbed a tree", verse: "Luke 19:2" },
      { word: "PRISCILLA", hint: "Wife of Aquila, co-worker of Paul", verse: "Romans 16:3" },
    ],
    people: [
      { word: "BARTIMAEUS", hint: "Blind man healed by Jesus in Jericho", verse: "Mark 10:46" },
      { word: "CORNELIUS", hint: "Roman centurion baptised by Peter", verse: "Acts 10:1" },
      { word: "APOLLOS", hint: "Eloquent preacher from Alexandria", verse: "Acts 18:24" },
      { word: "GAMALIEL", hint: "Respected Pharisee who defended the apostles", verse: "Acts 5:34" },
      { word: "ONESIMUS", hint: "Slave on whose behalf Paul wrote to Philemon", verse: "Philemon 1:10" },
      { word: "EPAPHRAS", hint: "Founder of the church at Colossae", verse: "Colossians 1:7" },
      { word: "TYCHICUS", hint: "Paul's trusted messenger and companion", verse: "Ephesians 6:21" },
      { word: "SOSTHENES", hint: "Co-author with Paul of 1 Corinthians", verse: "1 Corinthians 1:1" },
      { word: "ERASTUS", hint: "City treasurer who was Paul's companion", verse: "Romans 16:23" },
    ],
    places: [
      { word: "CAESAREA", hint: "Roman capital of Judea where Paul was imprisoned", verse: "Acts 23:33" },
      { word: "SILOAM", hint: "Pool where Jesus healed a blind man", verse: "John 9:7" },
      { word: "OLIVET", hint: "Mount of Olives near Jerusalem", verse: "Acts 1:12" },
      { word: "ICONIUM", hint: "City where Paul and Barnabas were nearly stoned", verse: "Acts 14:1" },
      { word: "LYSTRA", hint: "City where Paul was stoned and left for dead", verse: "Acts 14:19" },
      { word: "PERGAMUM", hint: "Church where Satan's throne was said to be", verse: "Revelation 2:12" },
      { word: "SMYRNA", hint: "Church told to be faithful unto death", verse: "Revelation 2:8" },
      { word: "SARDIS", hint: "Church with a reputation of being alive but dead", verse: "Revelation 3:1" },
    ],
  },

  hard: {
    old: [
      { word: "METHUSELAH", hint: "Oldest man in the Bible at 969 years", verse: "Genesis 5:27" },
      { word: "MELCHIZEDEK", hint: "Mysterious priest-king of Salem", verse: "Genesis 14:18" },
      { word: "JEHOSHAPHAT", hint: "Good king of Judah who sought God", verse: "2 Chronicles 17:3" },
      { word: "NEBUCHADNEZZAR", hint: "Babylonian king who destroyed Jerusalem", verse: "2 Kings 24:1" },
      { word: "ZECHARIAH", hint: "Post-exile prophet of visions and hope", verse: "Zechariah 1:1" },
      { word: "ZEPHANIAH", hint: "Prophet who warned of the day of the Lord", verse: "Zephaniah 1:1" },
      { word: "HABAKKUK", hint: "Prophet who questioned God's silence", verse: "Habakkuk 1:1" },
      { word: "OBADIAH", hint: "Shortest book of the Old Testament", verse: "Obadiah 1:1" },
      { word: "ZERUBBABEL", hint: "Leader who oversaw rebuilding of the temple", verse: "Ezra 3:2" },
      { word: "AHASUERUS", hint: "Persian king who married Esther", verse: "Esther 1:1" },
      { word: "MEPHIBOSHETH", hint: "Jonathan's lame son shown kindness by David", verse: "2 Samuel 9:6" },
      { word: "CIRCUMCISION", hint: "Sign of the covenant given to Abraham", verse: "Genesis 17:11" },
      { word: "RIGHTEOUSNESS", hint: "Being right with God through obedience and faith", verse: "Romans 4:3" },
      { word: "DEUTERONOMY", hint: "Fifth book of Moses; second giving of the law", verse: "Deuteronomy 1:1" },
      { word: "ECCLESIASTES", hint: "Book exploring the meaning of life", verse: "Ecclesiastes 1:2" },
      { word: "LAMENTATIONS", hint: "Book of mourning over Jerusalem's fall", verse: "Lamentations 1:1" },
      { word: "SENNACHERIB", hint: "Assyrian king whose army was destroyed by an angel", verse: "2 Kings 19:35" },
      { word: "TIGLATHPILESER", hint: "Assyrian king who conquered northern Israel", verse: "2 Kings 15:29" },
      { word: "SHALMANESER", hint: "Assyrian king who besieged Samaria", verse: "2 Kings 17:3" },
      { word: "ABIMELECH", hint: "King of Gerar who interacted with Abraham", verse: "Genesis 20:2" },
    ],
    new: [
      { word: "BARTHOLOMEW", hint: "Disciple also known as Nathanael", verse: "Matthew 10:3" },
      { word: "THADDAEUS", hint: "One of the twelve disciples", verse: "Matthew 10:3" },
      { word: "THEOPHILUS", hint: "Person to whom Luke addressed his Gospel and Acts", verse: "Luke 1:3" },
      { word: "PHILIPPIANS", hint: "Paul's letter of joy from prison", verse: "Philippians 1:1" },
      { word: "COLOSSIANS", hint: "Paul's letter affirming Christ's supremacy", verse: "Colossians 1:1" },
      { word: "THESSALONIANS", hint: "Paul's letter about the second coming", verse: "1 Thessalonians 1:1" },
      { word: "GETHSEMANE", hint: "Garden where Jesus prayed before his arrest", verse: "Matthew 26:36" },
      { word: "TRANSFIGURATION", hint: "Jesus appeared in glory on the mountain", verse: "Matthew 17:2" },
      { word: "JUSTIFICATION", hint: "Being declared righteous before God", verse: "Romans 5:1" },
      { word: "SANCTIFICATION", hint: "Process of being made holy", verse: "1 Thessalonians 4:3" },
      { word: "PREDESTINATION", hint: "God's foreordained plan for the elect", verse: "Romans 8:30" },
      { word: "LAODICEA", hint: "Lukewarm church rebuked in Revelation", verse: "Revelation 3:14" },
      { word: "PHILADELPHIA", hint: "Church commended for keeping the faith", verse: "Revelation 3:7" },
      { word: "ARMAGEDDON", hint: "Final battle described in Revelation", verse: "Revelation 16:16" },
      { word: "PROPITIATION", hint: "Atoning sacrifice that satisfies God's wrath", verse: "1 John 2:2" },
      { word: "INTERCESSION", hint: "Jesus continually does this for believers", verse: "Hebrews 7:25" },
      { word: "RECONCILIATION", hint: "Restoration of relationship between God and man", verse: "2 Corinthians 5:18" },
      { word: "INCARNATION", hint: "God becoming flesh in Jesus Christ", verse: "John 1:14" },
      { word: "ATONEMENT", hint: "Christ's work making us 'at one' with God", verse: "Romans 5:11" },
      { word: "SOVEREIGNTY", hint: "God's supreme authority over all creation", verse: "Psalm 103:19" },
      { word: "OMNISCIENCE", hint: "God knowing all things past, present, future", verse: "Psalm 139:1" },
      { word: "OMNIPRESENCE", hint: "God being present everywhere at once", verse: "Psalm 139:7" },
      { word: "OMNIPOTENCE", hint: "God's unlimited power over all things", verse: "Revelation 19:6" },
      { word: "TRIBULATION", hint: "Period of great suffering before Christ's return", verse: "Revelation 7:14" },
      { word: "MILLENNIUM", hint: "Thousand year reign described in Revelation 20", verse: "Revelation 20:2" },
      { word: "ANTICHRIST", hint: "The great opponent of Christ in end times", verse: "1 John 2:18" },
      { word: "THESSALONICA", hint: "City where Paul preached in Macedonia", verse: "Acts 17:1" },
      { word: "MESOPOTAMIA", hint: "Land between the rivers; ancient civilisation", verse: "Acts 7:2" },
      { word: "CAPPADOCIA", hint: "Region in Asia Minor, Jews from here at Pentecost", verse: "Acts 2:9" },
      { word: "THYATIRA", hint: "Church rebuked for tolerating false prophetess", verse: "Revelation 2:18" },
    ],
    people: [
      { word: "EPAPHRODITUS", hint: "Messenger from Philippi who served Paul in prison", verse: "Philippians 2:25" },
      { word: "ANDRONICUS", hint: "Relative of Paul, notable among the apostles", verse: "Romans 16:7" },
      { word: "HIERAPOLIS", hint: "City near Colossae where Epaphras ministered", verse: "Colossians 4:13" },
    ],
    places: [
      { word: "PERGAMUM", hint: "Church where Satan's throne was said to be", verse: "Revelation 2:12" },
      { word: "PHILADELPHIA", hint: "Church commended for keeping the faith", verse: "Revelation 3:7" },
      { word: "LAODICEA", hint: "Lukewarm church rebuked in Revelation", verse: "Revelation 3:14" },
    ],
  }
};

const END_VERSES = [
  { text: "I can do all things through Christ who strengthens me.", ref: "Philippians 4:13" },
  { text: "The Lord is my shepherd; I shall not want.", ref: "Psalm 23:1" },
  { text: "For God so loved the world that He gave His only Son.", ref: "John 3:16" },
  { text: "Trust in the Lord with all your heart.", ref: "Proverbs 3:5" },
  { text: "Be strong and courageous. Do not be afraid.", ref: "Joshua 1:9" },
  { text: "Love the Lord your God with all your heart.", ref: "Deuteronomy 6:5" },
  { text: "The joy of the Lord is your strength.", ref: "Nehemiah 8:10" },
  { text: "His mercies are new every morning.", ref: "Lamentations 3:23" },
  { text: "Rejoice always, pray continually, give thanks in all circumstances.", ref: "1 Thessalonians 5:16" },
  { text: "Be still and know that I am God.", ref: "Psalm 46:10" },
  { text: "For we walk by faith, not by sight.", ref: "2 Corinthians 5:7" },
  { text: "The Lord bless you and keep you.", ref: "Numbers 6:24" },
  { text: "Draw near to God and He will draw near to you.", ref: "James 4:8" },
  { text: "Your word is a lamp to my feet and a light to my path.", ref: "Psalm 119:105" },
  { text: "No weapon formed against you shall prosper.", ref: "Isaiah 54:17" },
  { text: "I am the resurrection and the life.", ref: "John 11:25" },
  { text: "Cast all your anxiety on Him because He cares for you.", ref: "1 Peter 5:7" },
  { text: "For I know the plans I have for you, declares the Lord.", ref: "Jeremiah 29:11" },
];

const WORD_OF_DAY_LIST = [
  { word: "GRACE", meaning: "The unmerited favour and love of God toward sinful humanity", verse: "Ephesians 2:8 — For it is by grace you have been saved, through faith." },
  { word: "SHALOM", meaning: "Hebrew word for peace — a wholeness and harmony in all areas of life", verse: "Numbers 6:26 — The Lord turn his face toward you and give you peace." },
  { word: "AGAPE", meaning: "The highest form of love — unconditional, selfless, divine love", verse: "1 John 4:8 — God is love." },
  { word: "LOGOS", meaning: "The Word; used in John 1 to describe Christ as the eternal Word of God", verse: "John 1:1 — In the beginning was the Word." },
  { word: "AMEN", meaning: "Hebrew for 'so be it' — an affirmation of truth and agreement", verse: "Revelation 22:20 — Amen. Come, Lord Jesus." },
  { word: "HALLELUJAH", meaning: "Hebrew praise meaning 'Praise the Lord'", verse: "Psalm 150:6 — Let everything that has breath praise the Lord!" },
  { word: "COVENANT", meaning: "A binding agreement between God and His people, sealed by oath", verse: "Hebrews 8:6 — The covenant of which He is mediator is better." },
  { word: "SABBATH", meaning: "The seventh day of rest; a holy gift of rest and reflection", verse: "Exodus 20:8 — Remember the Sabbath day by keeping it holy." },
  { word: "HOSANNA", meaning: "Hebrew cry of praise meaning 'Save now!' — shouted as Jesus entered Jerusalem", verse: "Matthew 21:9 — Hosanna to the Son of David!" },
  { word: "SELAH", meaning: "Hebrew musical term meaning pause and reflect — used 74 times in Psalms", verse: "Psalm 3:4 — He answers me from his holy mountain. Selah." },
  { word: "ATONEMENT", meaning: "The reconciling work of Christ — making humanity 'at one' with God", verse: "Romans 5:11 — We have now received reconciliation." },
  { word: "MARANATHA", meaning: "Aramaic phrase meaning 'Come, Lord' — a prayer for Christ's return", verse: "1 Corinthians 16:22 — Come, Lord!" },
  { word: "REPENTANCE", meaning: "A complete turning of the mind and heart toward God — not mere sorrow", verse: "Acts 3:19 — Repent and turn to God, so your sins may be wiped out." },
  { word: "RIGHTEOUSNESS", meaning: "Being in right standing with God — through faith, not works", verse: "Romans 4:3 — Abraham believed God and it was credited as righteousness." },
];
